"""Generate the reference pages of the documentation from the code.

Writes
  docs/reference/codes.md     every finding code from ``pycuf.findings.CODES``
  docs/reference/tables.md    every table schema from ``pycuf.tables.TABLES``
  docs/reference/glossary.md  every CUF-XML element and attribute from ``pycuf.spec.ELEMENTS``

Run after changing finding codes, table schemas or the catalogue (CI fails when stale):

    uv run python scripts/gen_docs.py           # rewrite the pages
    uv run python scripts/gen_docs.py --check   # exit 1 if a page is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from pycuf.findings import CODES
from pycuf.spec import ELEMENTS
from pycuf.tables import NUMBER, TABLES

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
NOTICE = (
    "<!-- Generated by scripts/gen_docs.py from {source}. Do not edit by hand: change the code\n"
    "     and run `uv run python scripts/gen_docs.py` (CI checks that this page is current). -->\n"
)
GROUPS = {
    "1": "Input and character encoding",
    "2": "XML well-formedness and security",
    "3": "Structure and values",
    "4": "Sort codes",
    "5": "Stated totals against computed totals",
    "7": "Data quality, conventions and lenient parsing",
}


def codes_page() -> str:
    out = [NOTICE.format(source="pycuf/findings.py"), "# Finding codes\n"]
    out.append(
        "Every problem pycuf notices is a finding with a stable code. Codes are never renumbered "
        "or reused. The severity shown is the default; change it with `severity_overrides`.\n"
    )
    for digit, title in GROUPS.items():
        out.append(f"\n## CUF{digit}xxx: {title}\n")
        out.append("| Code | Severity | Meaning |\n|---|---|---|")
        out.extend(
            f"| `{c.code}` | {c.severity.name} | {c.title} |"
            for c in CODES.values()
            if c.code[3] == digit
        )
    return "\n".join(out) + "\n"


def tables_page() -> str:
    p, s = NUMBER
    out = [NOTICE.format(source="pycuf/tables.py"), "# Table schemas\n"]
    out.append(
        f"Logical types: `string`, `int64`, `bool`, `date`, `timestamp` and `number`. A `number` "
        f"is a `decimal.Decimal` in Python and `decimal128({p}, {s})` in Arrow.\n"
    )
    for name, columns in TABLES.items():
        out.append(f"\n## `{name}`\n")
        out.append("| Column | Type |\n|---|---|")
        out.extend(f"| `{c.name}` | {c.type} |" for c in columns)
    return "\n".join(out) + "\n"


def glossary_page() -> str:
    out = [NOTICE.format(source="pycuf/spec.py"), "# Glossary: Dutch CUF-XML names\n"]
    out.append(
        "CUF-XML uses Dutch element and attribute names; pycuf's model uses English ones. This "
        "page maps every element to its class and every attribute to its field, with a short "
        "description. Required attributes are marked with ✱.\n"
    )
    for el in ELEMENTS.values():
        out.append(f"\n## `{el.name}` → `{el.model}`\n")
        out.append(f"{el.description}\n")
        if el.attributes:
            out.append("| Attribute | Field | Type | Meaning |\n|---|---|---|---|")
            for a in el.attributes.values():
                req = " ✱" if a.required else ""
                out.append(f"| `{a.name}`{req} | `{a.field}` | {a.type} | {a.description} |")
        if el.children:
            kids = ", ".join(f"`{k}`" for k in el.children)
            out.append(f"\nChild elements: {kids}.")
    return "\n".join(out) + "\n"


PAGES = {"codes.md": codes_page, "tables.md": tables_page, "glossary.md": glossary_page}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a page is out of date")
    args = parser.parse_args()
    stale = []
    REFERENCE.mkdir(parents=True, exist_ok=True)
    for name, build in PAGES.items():
        path = REFERENCE / name
        content = build()
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print(f"out of date: {', '.join(stale)}; run uv run python scripts/gen_docs.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
